apiVersion: v1
kind: Service
metadata:
  name: article
spec:
  selector:
    app: article
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article
  template:
    metadata:
      labels:
        app: article
    spec:
      containers:
        - name: article
          image: kimleangxama/article:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/article
            - name: PORT
              value: "3000"
          imagePullPolicy: Always